// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcskfmutqwjqpninskkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjc2tmbXV0cXdqcXBuaW5za2t3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMDUzNTIsImV4cCI6MjA1OTY4MTM1Mn0.JNu_2xpPzjFx-K2mH_4vfjJivtaDlfdDYgLRbD5M83U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);